import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='flex justify-center'> Logo </div>
        <div className='flex justify-center py-5'><Link href={{pathname: '/dashboard',query:{name:'Prame'}}}>Dashboard</Link> | <Link href='/dashboard/customers'>Customers</Link> | <Link href='/dashboard/reports'>Reports</Link> </div>
        {children}</body>
    </html>
  )
}
